- name: Provision VM
  hosts: all
  become: true
  pre_tasks:
    - name: Make sure that python3 and pip3 are installed
      ansible.builtin.apt:
        name: ["python3", "python3-pip"]
        state: present
        update_cache: true
  roles:
    - role: geerlingguy.postgresql
  tasks:
    - name: Append SSH key
      ansible.posix.authorized_key:
        user: vagrant
        key: "{{ lookup('file', 'files/id_rsa.pub') }}"
        state: present
